- name: Deploy Lychee on Kubernetes
  hosts: rke2_server[0]
  vars:
    kubernetes_files_dir: /root/kubernetes-files/lychee
    kubernetes_config_file: /etc/rancher/rke2/rke2.yaml
    ceph_csi_config_files:
      - common/ceph-conf.yaml
      - common/ceph-csi-configmap.yaml
      - common/ceph-cephfs-secrets.yaml
    ceph_csi_plugin_files:
      - csi-provisioner-rbac.yaml
      - csi-nodeplugin-rbac.yaml
      - csi-cephfsplugin-provisioner.yaml
      - csi-cephfsplugin.yaml
    lychee_kubernetes_files:
      - common/ceph-cephfs-sc.yaml
      - common/le-prod.yaml
      - common/redirectscheme.yaml
      - lychee/lychee-claim0-persistentvolumeclaim.yaml
      - lychee/lychee-claim1-persistentvolumeclaim.yaml
      - lychee/mariadb-claim0-persistentvolumeclaim.yaml
      - lychee/mariadb-deployment.yaml
      - lychee/mariadb-service.yaml
      - lychee/lychee-deployment.yaml
      - lychee/lychee-service.yaml
      - lychee/lychee-ingress.yaml

  tasks:
  - name: Make sure we have pip installed
    ansible.builtin.apt:
      name: python3-pip
      update_cache: yes

  - name: Install dependencies to run kubernetes module
    ansible.builtin.pip:
      name:
      - kubernetes>=12.0.0
      - openshift

  - name: Add jetstack chart repo
    kubernetes.core.helm_repository:
      name: jetstack
      repo_url: "https://charts.jetstack.io"

  - name: Deploy cert-manager helm chart
    kubernetes.core.helm:
      name: cert-manager
      chart_ref: jetstack/cert-manager
      release_namespace: cert-manager
      chart_version: v1.9.1
      create_namespace: true
      values:
        installCRDs: true
    environment:
      KUBECONFIG: "{{ kubernetes_config_file }}"

  - name: Create directory for kubernetes files
    ansible.builtin.file:
      path: "{{ kubernetes_files_dir }}"
      state: directory

  - name: Template kubernetes files for ceph-csi configuration
    ansible.builtin.template:
      src: kubernetes/{{ item }}
      dest: "{{ kubernetes_files_dir }}/{{ item | basename}}"
    with_items: "{{ ceph_csi_config_files }}"

  - name: Deploy kubernetes objects for ceph-csi configuration
    kubernetes.core.k8s:
      state: present
      src: "{{ kubernetes_files_dir }}/{{ item | basename }}"
      namespace: default
    with_items: "{{ ceph_csi_config_files }}"
    environment:
      KUBECONFIG: "{{ kubernetes_config_file }}"

  - name: Clone ceph-csi repo
    ansible.builtin.git:
      repo: https://github.com/ceph/ceph-csi.git
      dest: /opt/ceph-csi
      version: v3.6.2

  - name: Deploy ceph-csi
    kubernetes.core.k8s:
      state: present
      src: /opt/ceph-csi/deploy/cephfs/kubernetes/{{ item }}
      namespace: default
    with_items: "{{ ceph_csi_plugin_files}}"
    environment:
      KUBECONFIG: "{{ kubernetes_config_file }}"

  - name: Template kubernetes files for lychee
    ansible.builtin.template:
      src: kubernetes/{{ item }}
      dest: "{{ kubernetes_files_dir }}/{{ item | basename}}"
    with_items: "{{ lychee_kubernetes_files }}"

  - name: Deploy kubernetes files for lychee
    kubernetes.core.k8s:
      state: present
      src: "{{ kubernetes_files_dir }}/{{ item | basename}}"
      namespace: default
    with_items: "{{ lychee_kubernetes_files }}"
    environment:
      KUBECONFIG: "{{ kubernetes_config_file }}"
