apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: default
  labels:
    group : "monitoring"
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
  
spec:
  selector: 
    app: prometheus
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  sessionAffinity: None
  type: LoadBalancer