apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  labels:
    group : "monitoring"
  creationTimestamp: null
  name: prometheus-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-cephfs-sc
status: {}