- name: Deploy haste-server on Kubernetes
  hosts: k3s_server[0]
  vars:
    kubernetes_files_dir: /root/kubernetes-files/haste-server
    kubernetes_config_file: /etc/rancher/k3s/k3s.yaml
    kubernetes_files:
      - le-prod.yaml
      - redirectscheme.yaml
      - haste-server.yaml

  tasks:
  - name: Make sure we have pip installed
    ansible.builtin.apt:
      name: python3-pip
      update_cache: yes

  - name: Install dependencies to run kubernetes module
    ansible.builtin.pip:
      name:
      - kubernetes>=12.0.0

  - name: Add jetstack chart repo
    kubernetes.core.helm_repository:
      name: jetstack
      repo_url: "https://charts.jetstack.io"

  - name: Deploy cert-manager helm chart
    kubernetes.core.helm:
      name: cert-manager
      chart_ref: jetstack/cert-manager
      release_namespace: cert-manager
      chart_version: v1.9.1
      create_namespace: true
      values:
        installCRDs: true
    environment:
      KUBECONFIG: "{{ kubernetes_config_file }}"

  - name: Create directory for kubernetes files
    ansible.builtin.file:
      path: "{{ kubernetes_files_dir }}"
      state: directory

  - name: Copy kubernetes files
    ansible.builtin.copy:
      src: kubernetes/haste-server/{{ item }}
      dest: "{{ kubernetes_files_dir }}/{{ item }}"
    with_items: "{{ kubernetes_files }}"


  - name: Deploy kubernetes objects
    kubernetes.core.k8s:
      state: present
      src: "{{ kubernetes_files_dir }}/{{ item }}"
      namespace: default
    with_items: "{{ kubernetes_files }}"
    environment:
      KUBECONFIG: "{{ kubernetes_config_file }}"
