---
- name: add prereqs
  include_role:
    name: packages
  vars:
    packages_list:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: add docker apt key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_lsb.id|lower }}/gpg
  notify: apt update

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: get dpkg architecture
  shell: dpkg --print-architecture
  changed_when: false
  register: dpkg_arch

- name: prepare repo line
  ansible.builtin.set_fact:
    repo_line: "deb [arch={{ dpkg_arch.stdout }}] https://download.docker.com/linux/{{ ansible_lsb.id|lower }} {{ ansible_lsb.codename }} stable"

- name: add docker repo
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      {{ repo_line }}
  notify: apt update

- name: Force handlers to run 'apt update' if needed
  ansible.builtin.meta: flush_handlers

- name: add docker packages
  include_role:
    name: packages
  vars:
    packages_list:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin 
