---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: default
stringData:
  # Required for statically provisioned volumes
  userID: {{ common_ceph_user_id }}
  userKey: {{ common_ceph_user_key }}

  # Required for dynamically provisioned volumes
  adminID: {{ common_ceph_admin_id }}
  adminKey: {{ common_ceph_admin_key }}
