apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana-helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "grafana-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "grafana-helm.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: LoadBalancer
