apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-redirectscheme@kubernetescrd
    kubernetes.io/ingress.class: traefik

spec:
  rules:
    - host: {{ .Values.fqdn }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  {{ include "grafana-helm.fullname" . }}
                port:
                  number: {{ .Values.service.port }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress-with-ssl
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure

spec:
  rules:
    - host: {{ .Values.fqdn }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  {{ include "grafana-helm.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  tls:
  - hosts:
    - {{ .Values.fqdn }}
    secretName: {{ .Values.fqdn }}-tls

