apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap-datasources
  namespace: default
  labels:
    group : "monitoring"
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
              "orgId": 1,
              "version": 1,
              "name": "prometheus1",
              "type": "prometheus",
              "url": "http://prometheus:9090",
              "uid": "nWDR9ik4k",
              "isDefault": "true",
              "access": "proxy",
              "editable": "true"
            }
        ]
    }
