- name: Setup Load Balancers
  hosts: k3s_loadbalancers

  tasks:
  - name: Install HAProxy
    ansible.builtin.apt:
      update_cache: yes
      name: haproxy
      state: present

  - name: Collect all controllers
    ansible.builtin.set_fact:
      controllers: "{{ groups['k3s_master'] | map('extract', hostvars, ['ansible_host']) }}"

  - name: Create HAProxy configuration from template
    ansible.builtin.template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify: Restart HAProxy

  handlers:
  - name: Restart HAProxy
    ansible.builtin.systemd:
      name: haproxy
      state: restarted


